version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/server
hooks:
    AfterInstall:
        - location: deploy/install_dependencies.sh
          timeout: 3600
          runas: ubuntu
    ApplicationStart:
        - location: deploy/start_server.sh
          timeout: 300
          runas: root
    ApplicationStop:
        - location: deploy/stop_server.sh
          timeout: 300
          runas: root
